-- Q01: Display customer name, city, customer segment, order ID, order date, and order status for every order placed in 2025.
SELECT 
    c.customer_name, 
    c.city, 
    c.customer_segment, 
    o.order_id, 
    o.order_date, 
    o.order_status
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
WHERE YEAR(o.order_date) = 2025;

-- Q02: Find all customers from Gujarat who belong to the Premium or Enterprise segment. Display customer name, city, and segment.
SELECT customer_name, city, customer_segment
FROM Customers
WHERE state = 'Gujarat' AND customer_segment IN ('Premium', 'Enterprise');

-- Q03: Display all products whose unit price is between ₹5,000 and ₹20,000, sorted from highest price to lowest price.
SELECT product_name, unit_price
FROM Products
WHERE unit_price BETWEEN 5000 AND 20000
ORDER BY unit_price DESC;

-- Q04: Find all completed orders where the quantity is greater than 4. Display order ID, customer ID, product ID, quantity, and order date.
SELECT order_id, customer_id, product_id, quantity, order_date
FROM Orders
WHERE order_status = 'Completed' AND quantity > 4;

-- Q05: Display the five most expensive products. Show product name, category, and unit price.
SELECT TOP 5 product_name, category, unit_price
FROM Products
ORDER BY unit_price DESC;

-- Q06: Find the total number of customers in each customer segment.
SELECT customer_segment, COUNT(customer_id) AS total_customers
FROM Customers
GROUP BY customer_segment;

-- Q07: Calculate the total quantity of products ordered for each product.
SELECT p.product_id, p.product_name, ISNULL(SUM(o.quantity), 0) AS total_quantity_ordered
FROM Products p
LEFT JOIN Orders o ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name;

-- Q08: Find the average unit price of products in each category.
SELECT category, AVG(unit_price) AS avg_unit_price
FROM Products
GROUP BY category;

-- Q09: Find categories whose average product price is greater than ₹10,000.
SELECT category, AVG(unit_price) AS avg_unit_price
FROM Products
GROUP BY category
HAVING AVG(unit_price) > 10000;

-- Q10: Find customers who have placed at least 3 orders. Display customer ID and order count.
SELECT customer_id, COUNT(order_id) AS order_count
FROM Orders
GROUP BY customer_id
HAVING COUNT(order_id) >= 3;

-- Q11: Display customer name, order ID, product name, quantity, and unit price using an INNER JOIN between Customers, Orders, and Products.
SELECT c.customer_name, o.order_id, p.product_name, o.quantity, p.unit_price
FROM Customers c
INNER JOIN Orders o ON c.customer_id = o.customer_id
INNER JOIN Products p ON o.product_id = p.product_id;

-- Q12: Create a sales report showing customer name, product name, category, quantity, unit price, and calculated Total Value (quantity × unit price).
SELECT 
    c.customer_name, 
    p.product_name, 
    p.category, 
    o.quantity, 
    p.unit_price, 
    (o.quantity * p.unit_price) AS TotalValue
FROM Customers c
INNER JOIN Orders o ON c.customer_id = o.customer_id
INNER JOIN Products p ON o.product_id = p.product_id;

-- Q13: Find the total sales value generated by each customer, considering all orders. Display customer name and total sales value.
SELECT c.customer_name, SUM(o.quantity * p.unit_price) AS total_sales_value
FROM Customers c
INNER JOIN Orders o ON c.customer_id = o.customer_id
INNER JOIN Products p ON o.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name;

-- Q14: Find the total sales value for each product category. Display category and total sales value.
SELECT p.category, SUM(o.quantity * p.unit_price) AS total_sales_value
FROM Products p
INNER JOIN Orders o ON p.product_id = o.product_id
GROUP BY p.category;

-- Q15: Find the number of orders handled by each sales employee. Display employee name, department, and order count.
SELECT e.employee_name, e.department, COUNT(o.order_id) AS order_count
FROM Employees e
INNER JOIN Orders o ON e.employee_id = o.sales_employee_id
GROUP BY e.employee_id, e.employee_name, e.department;

-- Q16: Find sales employees who handled more than 8 orders.
SELECT e.employee_name, e.department, COUNT(o.order_id) AS order_count
FROM Employees e
INNER JOIN Orders o ON e.employee_id = o.sales_employee_id
GROUP BY e.employee_id, e.employee_name, e.department
HAVING COUNT(o.order_id) > 8;

-- Q17: Display all customers, including customers who have never placed an order. Show customer name, order ID, and order status.
SELECT c.customer_name, o.order_id, o.order_status
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id;

-- Q18: Find customers who have never placed an order using a LEFT JOIN.
SELECT c.customer_id, c.customer_name
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

-- Q19: Find products that have never appeared in an order.
SELECT p.product_id, p.product_name
FROM Products p
LEFT JOIN Orders o ON p.product_id = o.product_id
WHERE o.order_id IS NULL;

-- Q20: Display every product along with the total quantity sold. Products with no sales must still appear with quantity 0 or an equivalent result.
SELECT p.product_id, p.product_name, ISNULL(SUM(o.quantity), 0) AS total_quantity_sold
FROM Products p
LEFT JOIN Orders o ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name;

-- Q21: Find customers whose total completed-order value exceeds ₹150,000.
SELECT c.customer_id, c.customer_name, SUM(o.quantity * p.unit_price) AS total_completed_value
FROM Customers c
INNER JOIN Orders o ON c.customer_id = o.customer_id
INNER JOIN Products p ON o.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_id, c.customer_name
HAVING SUM(o.quantity * p.unit_price) > 150000;

-- Q22: Find each customer's completed-order count and completed-order value. Include customers with no completed orders.
SELECT 
    c.customer_id, 
    c.customer_name, 
    COUNT(o.order_id) AS completed_order_count, 
    ISNULL(SUM(o.quantity * p.unit_price), 0) AS completed_order_value
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id AND o.order_status = 'Completed'
LEFT JOIN Products p ON o.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name;

-- Q23: Find the top 5 customers by completed-order revenue.
SELECT TOP 5 c.customer_id, c.customer_name, SUM(o.quantity * p.unit_price) AS completed_revenue
FROM Customers c
INNER JOIN Orders o ON c.customer_id = o.customer_id
INNER JOIN Products p ON o.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_id, c.customer_name
ORDER BY completed_revenue DESC;

-- Q24: Find the product with the highest total quantity sold within each category. Do not use subqueries or window functions.
SELECT p1.category, p1.product_name, SUM(o1.quantity) AS total_quantity_sold
FROM Products p1
INNER JOIN Orders o1 ON p1.product_id = o1.product_id
GROUP BY p1.category, p1.product_id, p1.product_name
HAVING SUM(o1.quantity) >= ALL (
    SELECT SUM(o2.quantity)
    FROM Products p2
    INNER JOIN Orders o2 ON p2.product_id = o2.product_id
    WHERE p2.category = p1.category
    GROUP BY p2.product_id
);

-- Q25: Create a customer payment report showing customer name, order ID, order status, paid amount, and payment status.
SELECT c.customer_name, o.order_id, o.order_status, py.paid_amount, py.payment_status
FROM Customers c
INNER JOIN Orders o ON c.customer_id = o.customer_id
INNER JOIN Payments py ON o.order_id = py.order_id;

-- Q26: Find all completed orders for which the payment status is not Paid.
SELECT o.order_id, o.customer_id, o.order_status, py.payment_status
FROM Orders o
INNER JOIN Payments py ON o.order_id = py.order_id
WHERE o.order_status = 'Completed' AND py.payment_status <> 'Paid';

-- Q27: Find customers who have orders but no support tickets.
SELECT DISTINCT c.customer_id, c.customer_name
FROM Customers c
INNER JOIN Orders o ON c.customer_id = o.customer_id
LEFT JOIN SupportTickets st ON c.customer_id = st.customer_id
WHERE st.ticket_id IS NULL;

-- Q28: Find customers who have support tickets but no orders.
SELECT DISTINCT c.customer_id, c.customer_name
FROM Customers c
INNER JOIN SupportTickets st ON c.customer_id = st.customer_id
LEFT JOIN Orders o ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

-- Q29: Display all employees and the number of support tickets assigned to them, including employees with zero tickets.
SELECT e.employee_id, e.employee_name, COUNT(st.ticket_id) AS ticket_count
FROM Employees e
LEFT JOIN SupportTickets st ON e.employee_id = st.employee_id
GROUP BY e.employee_id, e.employee_name;

-- Q30: Find support employees who handled more than 2 tickets.
SELECT e.employee_id, e.employee_name, COUNT(st.ticket_id) AS ticket_count
FROM Employees e
INNER JOIN SupportTickets st ON e.employee_id = st.employee_id
GROUP BY e.employee_id, e.employee_name
HAVING COUNT(st.ticket_id) > 2;

-- Q31: Create a report containing customer name, order ID, product name, sales employee name, department, quantity, and total order value.
SELECT 
    c.customer_name, 
    o.order_id, 
    p.product_name, 
    e.employee_name AS sales_employee_name, 
    e.department, 
    o.quantity, 
    (o.quantity * p.unit_price) AS total_order_value
FROM Orders o
INNER JOIN Customers c ON o.customer_id = c.customer_id
INNER JOIN Products p ON o.product_id = p.product_id
INNER JOIN Employees e ON o.sales_employee_id = e.employee_id;

-- Q32: Find the total revenue generated by each sales employee from completed orders only.
SELECT e.employee_id, e.employee_name, SUM(o.quantity * p.unit_price) AS total_revenue
FROM Employees e
INNER JOIN Orders o ON e.employee_id = o.sales_employee_id
INNER JOIN Products p ON o.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY e.employee_id, e.employee_name;

-- Q33: Find sales employees whose completed-order revenue is greater than ₹500,000.
SELECT e.employee_id, e.employee_name, SUM(o.quantity * p.unit_price) AS total_revenue
FROM Employees e
INNER JOIN Orders o ON e.employee_id = o.sales_employee_id
INNER JOIN Products p ON o.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY e.employee_id, e.employee_name
HAVING SUM(o.quantity * p.unit_price) > 500000;

-- Q34: Find the total completed sales value by customer city.
SELECT c.city, SUM(o.quantity * p.unit_price) AS completed_sales_value
FROM Customers c
INNER JOIN Orders o ON c.customer_id = o.customer_id
INNER JOIN Products p ON o.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY c.city;

-- Q35: Find cities whose completed sales value is greater than ₹300,000.
SELECT c.city, SUM(o.quantity * p.unit_price) AS completed_sales_value
FROM Customers c
INNER JOIN Orders o ON c.customer_id = o.customer_id
INNER JOIN Products p ON o.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY c.city
HAVING SUM(o.quantity * p.unit_price) > 300000;

-- Q36: Using FULL OUTER JOIN, produce a comparison between customers with orders and customers represented in support tickets. Show customer ID, customer name, order ID, and ticket ID.
SELECT 
    COALESCE(c1.customer_id, c2.customer_id) AS customer_id, 
    COALESCE(c1.customer_name, c2.customer_name) AS customer_name, 
    o.order_id, 
    st.ticket_id
FROM Orders o
INNER JOIN Customers c1 ON o.customer_id = c1.customer_id
FULL OUTER JOIN SupportTickets st ON o.customer_id = st.customer_id
LEFT JOIN Customers c2 ON st.customer_id = c2.customer_id;

-- Q37: Using FULL OUTER JOIN, identify customers who exist only in the order activity or only in the support-ticket activity.
SELECT 
    COALESCE(c1.customer_id, c2.customer_id) AS customer_id, 
    COALESCE(c1.customer_name, c2.customer_name) AS customer_name,
    o.order_id,
    st.ticket_id
FROM Orders o
INNER JOIN Customers c1 ON o.customer_id = c1.customer_id
FULL OUTER JOIN SupportTickets st ON o.customer_id = st.customer_id
LEFT JOIN Customers c2 ON st.customer_id = c2.customer_id
WHERE o.order_id IS NULL OR st.ticket_id IS NULL;

-- Q38: Using RIGHT JOIN, display every employee from the Employees table and any sales orders assigned to them. Employees with no orders must also appear.
SELECT o.order_id, o.order_date, e.employee_id, e.employee_name
FROM Orders o
RIGHT JOIN Employees e ON o.sales_employee_id = e.employee_id;

-- Q39: Use CROSS JOIN to generate every possible combination of customer segment and product category. Display the segment and category.
SELECT DISTINCT c.customer_segment, p.category
FROM Customers c
CROSS JOIN Products p;

-- Q40: Use CROSS JOIN to generate every possible combination of sales employee and product category, then display the combinations sorted by employee name and category.
SELECT e.employee_name, p.category
FROM Employees e
CROSS JOIN (SELECT DISTINCT category FROM Products) p
WHERE e.department = 'Sales'
ORDER BY e.employee_name, p.category;

-- Q41: Find the number of distinct customers who purchased products from each product category.
SELECT p.category, COUNT(DISTINCT o.customer_id) AS distinct_customers
FROM Products p
INNER JOIN Orders o ON p.product_id = o.product_id
GROUP BY p.category;

-- Q42: Find product categories purchased by at least 5 different customers.
SELECT p.category, COUNT(DISTINCT o.customer_id) AS distinct_customers
FROM Products p
INNER JOIN Orders o ON p.product_id = o.product_id
GROUP BY p.category
HAVING COUNT(DISTINCT o.customer_id) >= 5;

-- Q43: Find customers who purchased at least 3 different products.
SELECT c.customer_id, c.customer_name, COUNT(DISTINCT o.product_id) AS distinct_products_purchased
FROM Customers c
INNER JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(DISTINCT o.product_id) >= 3;

-- Q44: Find the average completed order value for each customer segment.
SELECT c.customer_segment, AVG(o.quantity * p.unit_price) AS avg_completed_order_value
FROM Customers c
INNER JOIN Orders o ON c.customer_id = o.customer_id
INNER JOIN Products p ON o.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_segment;

-- Q45: Find customer segments whose average completed order value is greater than ₹50,000.
SELECT c.customer_segment, AVG(o.quantity * p.unit_price) AS avg_completed_order_value
FROM Customers c
INNER JOIN Orders o ON c.customer_id = o.customer_id
INNER JOIN Products p ON o.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_segment
HAVING AVG(o.quantity * p.unit_price) > 50000;

-- Q46: Create a business performance report by sales employee showing employee name, department, number of completed orders, total quantity sold, total revenue, and average order value.
SELECT 
    e.employee_name, 
    e.department, 
    COUNT(o.order_id) AS completed_orders, 
    SUM(o.quantity) AS total_quantity_sold, 
    SUM(o.quantity * p.unit_price) AS total_revenue, 
    AVG(o.quantity * p.unit_price) AS avg_order_value
FROM Employees e
INNER JOIN Orders o ON e.employee_id = o.sales_employee_id
INNER JOIN Products p ON o.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY e.employee_id, e.employee_name, e.department;

-- Q47: Find the sales employee with the highest completed-order revenue without using subqueries or window functions.
SELECT TOP 1 e.employee_id, e.employee_name, SUM(o.quantity * p.unit_price) AS total_revenue
FROM Employees e
INNER JOIN Orders o ON e.employee_id = o.sales_employee_id
INNER JOIN Products p ON o.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY e.employee_id, e.employee_name
ORDER BY total_revenue DESC;

-- Q48: Create a report for each product showing product name, category, current stock, total quantity ordered, completed sales value, and number of distinct customers who ordered it. Products with no orders must also appear.
SELECT 
    p.product_name, 
    p.category, 
    p.stock_quantity AS current_stock, 
    ISNULL(SUM(o.quantity), 0) AS total_quantity_ordered, 
    ISNULL(SUM(CASE WHEN o.order_status = 'Completed' THEN o.quantity * p.unit_price ELSE 0 END), 0) AS completed_sales_value, 
    COUNT(DISTINCT o.customer_id) AS distinct_customers
FROM Products p
LEFT JOIN Orders o ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name, p.category, p.stock_quantity;

-- Q49: For each customer segment, compare completed-order revenue for pairs of customers in the same segment. Display the two customer names and their revenues only when the first customer's revenue is greater than the second customer's revenue.
SELECT 
    c1.customer_segment, 
    c1.customer_name AS customer_1, 
    rev1.revenue AS revenue_1, 
    c2.customer_name AS customer_2, 
    rev2.revenue AS revenue_2
FROM (
    SELECT o.customer_id, SUM(o.quantity * p.unit_price) AS revenue
    FROM Orders o 
    INNER JOIN Products p ON o.product_id = p.product_id
    WHERE o.order_status = 'Completed'
    GROUP BY o.customer_id
) rev1
INNER JOIN Customers c1 ON rev1.customer_id = c1.customer_id
INNER JOIN Customers c2 ON c1.customer_segment = c2.customer_segment AND c1.customer_id <> c2.customer_id
INNER JOIN (
    SELECT o.customer_id, SUM(o.quantity * p.unit_price) AS revenue
    FROM Orders o 
    INNER JOIN Products p ON o.product_id = p.product_id
    WHERE o.order_status = 'Completed'
    GROUP BY o.customer_id
) rev2 ON c2.customer_id = rev2.customer_id
WHERE rev1.revenue > rev2.revenue;

-- Q50: Build a management-level sales report showing customer segment, number of customers, number of completed orders, total quantity sold, total revenue, and average order value. Include segments even if a metric has no matching records.
SELECT 
    c.customer_segment, 
    COUNT(DISTINCT c.customer_id) AS total_customers, 
    COUNT(DISTINCT CASE WHEN o.order_status = 'Completed' THEN o.order_id END) AS completed_orders, 
    ISNULL(SUM(CASE WHEN o.order_status = 'Completed' THEN o.quantity ELSE 0 END), 0) AS total_quantity_sold, 
    ISNULL(SUM(CASE WHEN o.order_status = 'Completed' THEN o.quantity * p.unit_price ELSE 0 END), 0) AS total_revenue, 
    ISNULL(AVG(CASE WHEN o.order_status = 'Completed' THEN o.quantity * p.unit_price END), 0) AS avg_order_value
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
LEFT JOIN Products p ON o.product_id = p.product_id
GROUP BY c.customer_segment;